import BlackwellApproachability

set_option autoImplicit false

/-
# Proof surface

The selected declarations mirror BlackwellChallenge.lean exactly. Their
proofs are short adapters to the independently named implementation facts.
-/

namespace Blackwell.Palomar

theorem blackwell_approachability_bound {E : Type*} [NormedAddCommGroup E]
    [InnerProductSpace ℝ E] {C : Set E} (x avg proj : ℕ → E) (B : ℝ)
    (hproj : ∀ t : ℕ, proj t ∈ C)
    (hmin : ∀ t : ℕ, ∀ z ∈ C,
      ‖avg t - proj t‖ ≤ ‖avg t - z‖)
    (havg : ∀ t : ℕ, ((t : ℝ) + 1) • avg (t + 1) =
      (t : ℝ) • avg t + x t)
    (hinner : ∀ t : ℕ,
      inner ℝ (avg t - proj t) (x t - proj t) ≤ 0)
    (hbound : ∀ t : ℕ, ‖x t - proj t‖ ≤ B) (hB : 0 ≤ B) :
    ∀ {T : ℕ}, 0 < T →
      Metric.infDist (avg T) C ≤ B / Real.sqrt T := by
  exact Blackwell.Approachability.blackwell_approachability_bound
    x avg proj B hproj hmin havg hinner hbound hB

/-- The running average generated by an explicit response function. -/
noncomputable def responseAverage {E : Type*} [AddCommGroup E] [Module ℝ E]
    (response : E → E) : ℕ → E
  | 0 => 0
  | t + 1 => ((t : ℝ) + 1)⁻¹ •
      ((t : ℝ) • responseAverage response t +
        response (responseAverage response t))

/-- Adapter to the checked sequential response-oracle implementation. -/
theorem blackwell_response_bound {E : Type*} [NormedAddCommGroup E]
    [InnerProductSpace ℝ E] {C : Set E} (response projection : E → E) (B : ℝ)
    (hproj : ∀ y : E, projection y ∈ C)
    (hmin : ∀ y : E, ∀ z ∈ C,
      ‖y - projection y‖ ≤ ‖y - z‖)
    (hinner : ∀ y : E,
      inner ℝ (y - projection y) (response y - projection y) ≤ 0)
    (hbound : ∀ y : E, ‖response y - projection y‖ ≤ B) (hB : 0 ≤ B) :
    ∀ {T : ℕ}, 0 < T →
      Metric.infDist (responseAverage response T) C ≤ B / Real.sqrt T := by
  intro T hT
  have hresponseAverage : ∀ n : ℕ,
      responseAverage response n =
        Blackwell.Approachability.responseAverage response n := by
    intro n
    induction n with
    | zero => rfl
    | succ n ih =>
        simp [responseAverage, Blackwell.Approachability.responseAverage, ih]
  rw [hresponseAverage T]
  exact Blackwell.Approachability.blackwell_response_bound response projection B
    hproj hmin hinner hbound hB (T := T) hT

theorem exists_projection {E : Type*} [NormedAddCommGroup E]
    [InnerProductSpace ℝ E] [CompleteSpace E] {C : Set E}
    (hne : C.Nonempty) (hclosed : IsClosed C) (hconvex : Convex ℝ C)
    (y : E) :
    ∃ p ∈ C, ‖y - p‖ = Metric.infDist y C ∧
      ∀ z ∈ C, inner ℝ (y - p) (z - p) ≤ 0 := by
  exact Blackwell.Approachability.exists_projection hne hclosed hconvex y

end Blackwell.Palomar
