import BlackwellApproachability

set_option autoImplicit false

/-
# Proof surface

The selected declarations mirror BlackwellChallenge.lean exactly. Their
proofs are short adapters to the independently named implementation facts.
-/

namespace Blackwell.Palomar

/-- The real scalar action supplied by the inner-product-space instance.
    Naming it keeps the proof surface definitionally aligned with the
    independent Challenge signature. -/
def real_smul {E : Type*} [NormedAddCommGroup E]
    [InnerProductSpace ℝ E] (r : ℝ) (x : E) : E := r • x

/-- The usual Mathlib convexity predicate for the real scalar action. -/
def real_convex {E : Type*} [NormedAddCommGroup E]
    [InnerProductSpace ℝ E] (C : Set E) : Prop := Convex ℝ C

theorem blackwell_approachability_bound {E : Type*} [NormedAddCommGroup E]
    [InnerProductSpace ℝ E] {C : Set E} (x avg proj : ℕ → E) (B : ℝ)
    (hproj : ∀ t : ℕ, proj t ∈ C)
    (hmin : ∀ t : ℕ, ∀ z ∈ C,
      ‖avg t - proj t‖ ≤ ‖avg t - z‖)
    (havg : ∀ t : ℕ, real_smul ((t : ℝ) + 1) (avg (t + 1)) =
      real_smul (t : ℝ) (avg t) + x t)
    (hinner : ∀ t : ℕ,
      inner ℝ (avg t - proj t) (x t - proj t) ≤ 0)
    (hbound : ∀ t : ℕ, ‖x t - proj t‖ ≤ B) (hB : 0 ≤ B) :
    ∀ {T : ℕ}, 0 < T →
      Metric.infDist (avg T) C ≤ B / Real.sqrt T := by
  intro T hT
  apply Blackwell.Approachability.blackwell_approachability_bound
    x avg proj B hproj hmin ?_ hinner hbound hB (T := T) hT
  intro t
  simpa [real_smul] using havg t

/-- The running average generated by an explicit response function. -/
noncomputable def responseAverage {E : Type*} [NormedAddCommGroup E]
    [InnerProductSpace ℝ E]
    (response : E → E) : ℕ → E
  | 0 => 0
  | t + 1 => real_smul (((t : ℝ) + 1)⁻¹)
      (real_smul (t : ℝ) (responseAverage response t) +
        response (responseAverage response t))

/-- Adapter to the checked sequential response-oracle implementation. -/
theorem blackwell_response_bound {E : Type*} [NormedAddCommGroup E]
    [InnerProductSpace ℝ E] {C : Set E} (response projection : E → E) (B : ℝ)
    (hproj : ∀ y : E, projection y ∈ C)
    (hmin : ∀ y : E, ∀ z ∈ C,
      ‖y - projection y‖ ≤ ‖y - z‖)
    (hinner : ∀ y : E,
      inner ℝ (y - projection y) (response y - projection y) ≤ 0)
    (hbound : ∀ y : E, ‖response y - projection y‖ ≤ B) (hB : 0 ≤ B) :
    ∀ {T : ℕ}, 0 < T →
      Metric.infDist (responseAverage response T) C ≤ B / Real.sqrt T := by
  intro T hT
  have hresponseAverage : ∀ n : ℕ,
      responseAverage response n =
        Blackwell.Approachability.responseAverage response n := by
    intro n
    induction n with
    | zero => rfl
    | succ n ih =>
        simp [responseAverage, Blackwell.Approachability.responseAverage, real_smul, ih]
  rw [hresponseAverage T]
  exact Blackwell.Approachability.blackwell_response_bound response projection B
    hproj hmin hinner hbound hB (T := T) hT

theorem exists_projection {E : Type*} [NormedAddCommGroup E]
    [InnerProductSpace ℝ E] [CompleteSpace E] {C : Set E}
    (hne : C.Nonempty) (hclosed : IsClosed C) (hconvex : real_convex C)
    (y : E) :
    ∃ p ∈ C, ‖y - p‖ = Metric.infDist y C ∧
      ∀ z ∈ C, inner ℝ (y - p) (z - p) ≤ 0 := by
  exact Blackwell.Approachability.exists_projection hne hclosed
    (by simpa [real_convex] using hconvex) y

end Blackwell.Palomar
